---
baseURL: https://gophersfrm.netlify.com/
languageCode: en-us
title: Frankfurt Rhein-Main Gophers Meetup
theme: hugo-initio
params:
  description: Meetup group in Frankfurt/Germany
  homepage: https://gophersfrm.netlify.com/
  DateForm: January 2, 2006
  showSubheader: true
  showServices: false
  showDownload: true
  showClients: false
  address: Frankfurt, Leipziger Strasse 12
  name: Frankfurt Rhein-Main Gophers Meetup
  email: golangFrankfurt@gmail.com
  phone: "+49123456"
  year: 2019
  background: ''
  favicon: images/gt_favicon.png
  footerEnableContact: true
  footerEnableFollowme: true
  social:
  - title: twitter
    url: https://twitter.com/golangFrankfurt
    icon: fa-twitter-square
    footer: true
    sharethis: true
    network: twitter
  - title: email
    url: mailto:golangfrankfurt@gmail.com
    icon: fa-envelope
    footer: true
    sharethis: true
    network: twitter
menu:
  main:
  - name: support us
    url: "/support"
    weight: 10
  - name: hosts
    url: "/hosts"
    weight: 4
  - name: join
    url: "/join"
    weight: 3
  - name: about us
    url: "/about"
    weight: 2
  - name: home
    url: "/"
    weight: 1
min_version: 0.18
